# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include(joinpath(@__DIR__, "support", "SeededFuzz.jl"))
import .SeededFuzz

const MAX_REPLAY_BYTES = 8 * 1024 * 1024

function _readmutation(path::AbstractString)
    filesize(path) <= MAX_REPLAY_BYTES ||
        throw(ArgumentError("mutation file exceeds the 8 MiB replay limit: $path"))
    bytes = open(path, "r") do io
        read(io, MAX_REPLAY_BYTES + 1)
    end
    length(bytes) <= MAX_REPLAY_BYTES ||
        throw(ArgumentError("mutation file grew beyond the 8 MiB replay limit: $path"))
    return bytes
end

function _usage(io::IO=stdout)
    println(
        io,
        """
        Usage: julia --project=. test/fuzz.jl [options]

          --seed VALUE       Master UInt64 seed (decimal or 0x-prefixed hex)
          --cases N          Differential cases (default: $(SeededFuzz.EXTENDED_CASES))
          --mutations N      Byte mutations (default: $(SeededFuzz.EXTENDED_MUTATIONS))
          --case-index N     Replay exactly one generated differential case
          --mutation-index N Replay exactly one generated byte mutation
          --mutation-file P  Replay saved bytes instead of generating a case
          --mutation-lane L  stream_full, file_full, file_ranged, auto_full, or stats_filtered
          --layouts-only     Run only the deterministic layout-family lanes
          --skip-layouts     Skip layout-family lanes during an exact replay
          --determinism-every N
                             Repeat every Nth mutation plus the first route sweep
          --repro-dir PATH   Write deterministic failure artifacts to PATH
          --help             Show this help

        Set either count to zero to skip that generated lane. Saved-byte mode
        requires --mutation-lane and does not run generated lanes.
        """,
    )
    return nothing
end

_parseargs(args) = SeededFuzz.parse_options(args)

function _printmutationcounts(summary::SeededFuzz.MutationSummary)
    entries = sort!(collect(summary.counts); by=entry -> String(first(entry)))
    println("mutation classifications:")
    for (category, count) in entries
        println("  $category: $count")
    end
    println("mutation routes covered: $(length(summary.routecounts))")
    println("mutation determinism checks: $(summary.determinismchecks)")
    operations = sort!(collect(summary.operationcounts); by=entry -> String(first(entry)))
    println("mutation operations:")
    for (operation, count) in operations
        println("  $operation: $count")
    end
    return nothing
end

function main(args=ARGS)
    options = try
        _parseargs(args)
    catch err
        err isa ArgumentError || rethrow()
        showerror(stderr, err)
        println(stderr)
        _usage(stderr)
        return 2
    end
    if options.help
        _usage()
        return 0
    end

    println("$(SeededFuzz._environmenttext())")
    if options.mutation_file !== nothing
        path = abspath(options.mutation_file)
        isfile(path) || throw(ArgumentError("mutation file does not exist: $path"))
        result = SeededFuzz.replay_mutation(_readmutation(path), options.mutation_lane)
        println("saved mutation: $path")
        println("mutation lane: $(options.mutation_lane)")
        println("mutation determinism replay: enabled")
        println("classification: $(result.category)")
        result.details === nothing || println(result.details)
        return result.category === :unexpected ? 1 : 0
    end

    cases = options.layouts_only ? 0 : options.cases
    mutations = options.layouts_only ? 0 : options.mutations
    displayedcases = options.case_index === nothing ? cases : 1
    displayedmutations = options.mutation_index === nothing ? mutations : 1

    println("seed: 0x$(string(options.seed; base=16))")
    println("differential cases: $displayedcases")
    options.case_index === nothing || begin
        println("differential replay index: $(options.case_index)")
        println(
            "differential fingerprint: 0x$(string(SeededFuzz.case_fingerprint(options.seed, options.case_index); base=16))",
        )
    end
    println("byte mutations: $displayedmutations")
    options.mutation_index === nothing ||
        println("mutation replay index: $(options.mutation_index)")
    options.verify_determinism && println("mutation determinism replay: enabled")
    options.determinism_every > 0 && println(
        "mutation determinism sample: every $(options.determinism_every), plus route sweep",
    )
    println("layout-family lanes: $(options.include_layouts ? "enabled" : "disabled")")
    options.reproduction_dir === nothing ||
        println("failure artifacts: $(abspath(options.reproduction_dir))")

    summary = SeededFuzz.run_suite(;
        seed=options.seed,
        cases,
        mutations,
        case_index=options.case_index,
        mutation_index=options.mutation_index,
        include_layouts=options.include_layouts,
        reproduction_dir=options.reproduction_dir,
        verify_determinism=options.verify_determinism,
        determinism_every=options.determinism_every,
        progress_io=stdout,
    )
    differential = summary.differential
    println(
        "differential summary: cases=$(differential.cases) " *
        "variants=$(differential.variants) rewrites=$(differential.rewrites) " *
        "scan_checks=$(differential.scanchecks) layout_checks=$(differential.layoutchecks)",
    )
    println(
        "differential coverage: " *
        join(sort!(String.(collect(differential.coverage))), ", "),
    )

    _printmutationcounts(summary.mutations)
    println("fuzz run complete")
    return 0
end

if abspath(PROGRAM_FILE) == @__FILE__
    exit(main())
end
