# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

@testset "RunEndEncoded" begin
    @testset "PyArrow generated simple file" begin
        # Test reading the simple REE file generated by PyArrow
        # File contains: [1, 1, 1, 2, 2]
        file_path = joinpath(@__DIR__, "test_ree_simple.arrow")
        tbl = Arrow.Table(file_path)

        @test length(tbl) == 5
        @test propertynames(tbl) == (:simple_ree,)

        col = tbl.simple_ree
        @test col isa Arrow.RunEndEncoded
        @test length(col) == 5

        # Test indexing
        @test col[1] == 1
        @test col[2] == 1
        @test col[3] == 1
        @test col[4] == 2
        @test col[5] == 2

        # Test collecting
        @test collect(col) == [1, 1, 1, 2, 2]

        # Test iteration
        result = Int64[]
        for x in col
            push!(result, x)
        end
        @test result == [1, 1, 1, 2, 2]
    end

    @testset "PyArrow generated comprehensive file" begin
        # Test reading the comprehensive REE file with multiple column types
        # All columns have 10 elements
        file_path = joinpath(@__DIR__, "test_ree_data.arrow")
        tbl = Arrow.Table(file_path)

        @test length(tbl) == 10
        @test :ree_int in propertynames(tbl)
        @test :ree_float_with_nulls in propertynames(tbl)
        @test :ree_string in propertynames(tbl)
        @test :ree_int16_ends in propertynames(tbl)
        @test :ree_single_run in propertynames(tbl)
        @test :ree_bool in propertynames(tbl)

        # Test integer column: [1,1,1,1,2,2,3,3,3,3]
        col_int = tbl.ree_int
        @test col_int isa Arrow.RunEndEncoded
        @test length(col_int) == 10
        @test collect(col_int) == [1, 1, 1, 1, 2, 2, 3, 3, 3, 3]
        @test col_int[1] == 1
        @test col_int[4] == 1
        @test col_int[5] == 2
        @test col_int[6] == 2
        @test col_int[7] == 3
        @test col_int[10] == 3

        # Test float column with nulls: [1.0,1.0,1.0,1.0,null,null,2.0,2.0,2.0,2.0]
        col_float = tbl.ree_float_with_nulls
        @test col_float isa Arrow.RunEndEncoded
        @test length(col_float) == 10
        @test col_float[1] == 1.0
        @test col_float[4] == 1.0
        @test ismissing(col_float[5])
        @test ismissing(col_float[6])
        @test col_float[7] == 2.0
        @test col_float[10] == 2.0

        # Test string column: ["hello","hello","hello","world","world","foo","foo","foo","foo","foo"]
        col_string = tbl.ree_string
        @test col_string isa Arrow.RunEndEncoded
        @test length(col_string) == 10
        @test col_string[1] == "hello"
        @test col_string[3] == "hello"
        @test col_string[4] == "world"
        @test col_string[5] == "world"
        @test col_string[6] == "foo"
        @test col_string[10] == "foo"

        # Test Int16 run_ends: [100,100,100,100,100,200,200,200,200,200]
        col_int16 = tbl.ree_int16_ends
        @test col_int16 isa Arrow.RunEndEncoded
        @test length(col_int16) == 10
        @test collect(col_int16) == [100, 100, 100, 100, 100, 200, 200, 200, 200, 200]
        @test col_int16[1] == 100
        @test col_int16[5] == 100
        @test col_int16[6] == 200
        @test col_int16[10] == 200

        # Test single run: [42,42,42,42,42,42,42,42,42,42]
        col_single = tbl.ree_single_run
        @test col_single isa Arrow.RunEndEncoded
        @test length(col_single) == 10
        @test all(x -> x == 42, col_single)
        @test collect(col_single) == fill(42, 10)

        # Test boolean: [True,True,True,False,False,True,True,True,True,True]
        col_bool = tbl.ree_bool
        @test col_bool isa Arrow.RunEndEncoded
        @test length(col_bool) == 10
        @test col_bool[1] == true
        @test col_bool[3] == true
        @test col_bool[4] == false
        @test col_bool[5] == false
        @test col_bool[6] == true
        @test col_bool[10] == true
    end

    @testset "Julia round-trip tests" begin
        # Test writing and reading back REE arrays

        @testset "Simple repeated values" begin
            data = (col1=[1, 1, 1, 2, 2],)
            io = Arrow.tobuffer(data)
            tbl = Arrow.Table(io)
            @test collect(tbl.col1) == [1, 1, 1, 2, 2]
        end

        @testset "With missing values" begin
            data = (col1=[1.0, 1.0, missing, missing, 2.0],)
            io = Arrow.tobuffer(data)
            tbl = Arrow.Table(io)
            result = collect(tbl.col1)
            @test result[1] == 1.0
            @test result[2] == 1.0
            @test ismissing(result[3])
            @test ismissing(result[4])
            @test result[5] == 2.0
        end

        @testset "String values" begin
            data = (col1=["hello", "hello", "world", "world", "world"],)
            io = Arrow.tobuffer(data)
            tbl = Arrow.Table(io)
            @test collect(tbl.col1) == ["hello", "hello", "world", "world", "world"]
        end

        @testset "All same value (single run)" begin
            data = (col1=fill(42, 100),)
            io = Arrow.tobuffer(data)
            tbl = Arrow.Table(io)
            @test all(x -> x == 42, tbl.col1)
            @test length(tbl.col1) == 100
        end

        @testset "Boolean values" begin
            data = (col1=[true, true, false, false, true],)
            io = Arrow.tobuffer(data)
            tbl = Arrow.Table(io)
            @test collect(tbl.col1) == [true, true, false, false, true]
        end
    end

    @testset "Edge cases" begin
        @testset "Alternating values (no runs)" begin
            # This is a worst case for REE - every value is different
            data = (col1=[1, 2, 1, 2, 1, 2],)
            io = Arrow.tobuffer(data)
            tbl = Arrow.Table(io)
            @test collect(tbl.col1) == [1, 2, 1, 2, 1, 2]
        end

        @testset "Long runs" begin
            data = (col1=vcat(fill(1, 1000), fill(2, 1000), fill(3, 1000)),)
            io = Arrow.tobuffer(data)
            tbl = Arrow.Table(io)
            col = tbl.col1
            @test length(col) == 3000
            @test all(x -> x == 1, col[1:1000])
            @test all(x -> x == 2, col[1001:2000])
            @test all(x -> x == 3, col[2001:3000])
        end
    end
end
