# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# GENERATED by core/tools/fbsgen.jl from apache/arrow format/{Schema,File,Message}.fbs —
# do not edit by hand; rerun the generator against the current spec.

function verify_Null(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Null")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_Null(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Null(bytes, root, ctx, 0)
    return nothing
end

function verify_Struct(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Struct")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_Struct(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Struct(bytes, root, ctx, 0)
    return nothing
end

function verify_List(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "List")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_List(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_List(bytes, root, ctx, 0)
    return nothing
end

function verify_LargeList(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "LargeList")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_LargeList(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_LargeList(bytes, root, ctx, 0)
    return nothing
end

function verify_ListView(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "ListView")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_ListView(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_ListView(bytes, root, ctx, 0)
    return nothing
end

function verify_LargeListView(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "LargeListView")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_LargeListView(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_LargeListView(bytes, root, ctx, 0)
    return nothing
end

function verify_FixedSizeList(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "FixedSizeList")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vfield(t, 0, 4)
    return nothing
end

function verifyroot_FixedSizeList(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_FixedSizeList(bytes, root, ctx, 0)
    return nothing
end

function verify_Map(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Map")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vbool(t, 0)
    return nothing
end

function verifyroot_Map(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Map(bytes, root, ctx, 0)
    return nothing
end

function verify_Union(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Union")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001,))
    _vvector(t, 1, 4, ctx)
    return nothing
end

function verifyroot_Union(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Union(bytes, root, ctx, 0)
    return nothing
end

function verify_Int(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Int")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vfield(t, 0, 4)
    _vbool(t, 1)
    return nothing
end

function verifyroot_Int(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Int(bytes, root, ctx, 0)
    return nothing
end

function verify_FloatingPoint(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "FloatingPoint")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002,))
    return nothing
end

function verifyroot_FloatingPoint(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_FloatingPoint(bytes, root, ctx, 0)
    return nothing
end

function verify_Utf8(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Utf8")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_Utf8(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Utf8(bytes, root, ctx, 0)
    return nothing
end

function verify_Binary(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Binary")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_Binary(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Binary(bytes, root, ctx, 0)
    return nothing
end

function verify_LargeUtf8(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "LargeUtf8")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_LargeUtf8(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_LargeUtf8(bytes, root, ctx, 0)
    return nothing
end

function verify_LargeBinary(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "LargeBinary")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_LargeBinary(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_LargeBinary(bytes, root, ctx, 0)
    return nothing
end

function verify_Utf8View(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Utf8View")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_Utf8View(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Utf8View(bytes, root, ctx, 0)
    return nothing
end

function verify_BinaryView(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "BinaryView")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_BinaryView(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_BinaryView(bytes, root, ctx, 0)
    return nothing
end

function verify_FixedSizeBinary(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "FixedSizeBinary")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vfield(t, 0, 4)
    return nothing
end

function verifyroot_FixedSizeBinary(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_FixedSizeBinary(bytes, root, ctx, 0)
    return nothing
end

function verify_Bool(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Bool")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_Bool(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Bool(bytes, root, ctx, 0)
    return nothing
end

function verify_RunEndEncoded(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "RunEndEncoded")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    return nothing
end

function verifyroot_RunEndEncoded(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_RunEndEncoded(bytes, root, ctx, 0)
    return nothing
end

function verify_Decimal(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Decimal")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vfield(t, 0, 4)
    _vfield(t, 1, 4)
    _vfield(t, 2, 4)
    return nothing
end

function verifyroot_Decimal(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Decimal(bytes, root, ctx, 0)
    return nothing
end

function verify_Date(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Date")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001,))
    return nothing
end

function verifyroot_Date(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Date(bytes, root, ctx, 0)
    return nothing
end

function verify_Time(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Time")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002, 0x0000000000000003,))
    _vfield(t, 1, 4)
    return nothing
end

function verifyroot_Time(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Time(bytes, root, ctx, 0)
    return nothing
end

function verify_Timestamp(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Timestamp")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002, 0x0000000000000003,))
    _vstring(t, 1, ctx)
    return nothing
end

function verifyroot_Timestamp(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Timestamp(bytes, root, ctx, 0)
    return nothing
end

function verify_Interval(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Interval")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002,))
    return nothing
end

function verifyroot_Interval(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Interval(bytes, root, ctx, 0)
    return nothing
end

function verify_Duration(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Duration")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002, 0x0000000000000003,))
    return nothing
end

function verifyroot_Duration(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Duration(bytes, root, ctx, 0)
    return nothing
end

function verify_KeyValue(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "KeyValue")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vstring(t, 0, ctx; required=true)
    _vstring(t, 1, ctx; required=true)
    return nothing
end

function verifyroot_KeyValue(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_KeyValue(bytes, root, ctx, 0)
    return nothing
end

function verify_DictionaryEncoding(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "DictionaryEncoding")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vfield(t, 0, 8)
    p = _vref(t, 1)
    p === nothing || verify_Int(bytes, p, ctx, depth + 1)
    _vbool(t, 2)
    _venum(t, 3, 2, (0x0000000000000000,))
    return nothing
end

function verifyroot_DictionaryEncoding(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_DictionaryEncoding(bytes, root, ctx, 0)
    return nothing
end

function verify_Field(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Field")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vstring(t, 0, ctx)
    _vbool(t, 1)
    tagp = _vfield(t, 2, 1; required=true)
    tag = tagp === nothing ? 0x00 : _vu8(bytes, tagp)
    tag != 0x00 || _vfail("Field.type union tag is required")
    valp = _vref(t, 3; required=true)
    if tag == 0x00
        valp === nothing ||
            _vfail("Field.type union has a value but no tag")
    elseif tag == 0x01
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Null(bytes, valp, ctx, depth + 1)
    elseif tag == 0x02
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Int(bytes, valp, ctx, depth + 1)
    elseif tag == 0x03
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_FloatingPoint(bytes, valp, ctx, depth + 1)
    elseif tag == 0x04
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Binary(bytes, valp, ctx, depth + 1)
    elseif tag == 0x05
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Utf8(bytes, valp, ctx, depth + 1)
    elseif tag == 0x06
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Bool(bytes, valp, ctx, depth + 1)
    elseif tag == 0x07
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Decimal(bytes, valp, ctx, depth + 1)
    elseif tag == 0x08
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Date(bytes, valp, ctx, depth + 1)
    elseif tag == 0x09
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Time(bytes, valp, ctx, depth + 1)
    elseif tag == 0x0a
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Timestamp(bytes, valp, ctx, depth + 1)
    elseif tag == 0x0b
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Interval(bytes, valp, ctx, depth + 1)
    elseif tag == 0x0c
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_List(bytes, valp, ctx, depth + 1)
    elseif tag == 0x0d
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Struct(bytes, valp, ctx, depth + 1)
    elseif tag == 0x0e
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Union(bytes, valp, ctx, depth + 1)
    elseif tag == 0x0f
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_FixedSizeBinary(bytes, valp, ctx, depth + 1)
    elseif tag == 0x10
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_FixedSizeList(bytes, valp, ctx, depth + 1)
    elseif tag == 0x11
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Map(bytes, valp, ctx, depth + 1)
    elseif tag == 0x12
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Duration(bytes, valp, ctx, depth + 1)
    elseif tag == 0x13
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_LargeBinary(bytes, valp, ctx, depth + 1)
    elseif tag == 0x14
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_LargeUtf8(bytes, valp, ctx, depth + 1)
    elseif tag == 0x15
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_LargeList(bytes, valp, ctx, depth + 1)
    elseif tag == 0x16
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_RunEndEncoded(bytes, valp, ctx, depth + 1)
    elseif tag == 0x17
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_BinaryView(bytes, valp, ctx, depth + 1)
    elseif tag == 0x18
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_Utf8View(bytes, valp, ctx, depth + 1)
    elseif tag == 0x19
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_ListView(bytes, valp, ctx, depth + 1)
    elseif tag == 0x1a
        valp === nothing &&
            _vfail("Field.type union has a tag but no value")
        verify_LargeListView(bytes, valp, ctx, depth + 1)
    else
        _vfail("Field.type union has unknown tag")
    end
    p = _vref(t, 4)
    p === nothing || verify_DictionaryEncoding(bytes, p, ctx, depth + 1)
    _vtablevector(t, 5, verify_Field, ctx, depth)
    _vtablevector(t, 6, verify_KeyValue, ctx, depth)
    return nothing
end

function verifyroot_Field(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Field(bytes, root, ctx, 0)
    return nothing
end

function verify_Schema(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Schema")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001,))
    _vtablevector(t, 1, verify_Field, ctx, depth; required=true)
    _vtablevector(t, 2, verify_KeyValue, ctx, depth)
    _venumvector(t, 3, 8, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002,), ctx, "Schema.features")
    return nothing
end

function verifyroot_Schema(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Schema(bytes, root, ctx, 0)
    return nothing
end

function verify_Footer(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Footer")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002, 0x0000000000000003, 0x0000000000000004,))
    p = _vref(t, 1; required=true)
    p === nothing || verify_Schema(bytes, p, ctx, depth + 1)
    _vvector(t, 2, 24, ctx)
    _vvector(t, 3, 24, ctx)
    _vtablevector(t, 4, verify_KeyValue, ctx, depth)
    return nothing
end

function verifyroot_Footer(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Footer(bytes, root, ctx, 0)
    return nothing
end

function verify_BodyCompression(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "BodyCompression")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 1, (0x0000000000000000, 0x0000000000000001,))
    _venum(t, 1, 1, (0x0000000000000000,))
    return nothing
end

function verifyroot_BodyCompression(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_BodyCompression(bytes, root, ctx, 0)
    return nothing
end

function verify_RecordBatch(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "RecordBatch")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vfield(t, 0, 8)
    _vvector(t, 1, 16, ctx)
    _vvector(t, 2, 16, ctx)
    p = _vref(t, 3)
    p === nothing || verify_BodyCompression(bytes, p, ctx, depth + 1)
    _vvector(t, 4, 8, ctx)
    return nothing
end

function verifyroot_RecordBatch(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_RecordBatch(bytes, root, ctx, 0)
    return nothing
end

function verify_DictionaryBatch(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "DictionaryBatch")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _vfield(t, 0, 8)
    p = _vref(t, 1; required=true)
    p === nothing || verify_RecordBatch(bytes, p, ctx, depth + 1)
    _vbool(t, 2)
    return nothing
end

function verifyroot_DictionaryBatch(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_DictionaryBatch(bytes, root, ctx, 0)
    return nothing
end

function verify_Message(bytes::Vector{UInt8}, pos::Int64, ctx::VerifyContext, depth::Base.Int)
    t = _vtable(bytes, pos)
    _vvisit!(ctx, "Message")
    depth <= ctx.maxdepth || _vfail("metadata nesting exceeds limit")
    _venum(t, 0, 2, (0x0000000000000000, 0x0000000000000001, 0x0000000000000002, 0x0000000000000003, 0x0000000000000004,))
    tagp = _vfield(t, 1, 1; required=true)
    tag = tagp === nothing ? 0x00 : _vu8(bytes, tagp)
    tag != 0x00 || _vfail("Message.header union tag is required")
    valp = _vref(t, 2; required=true)
    if tag == 0x00
        valp === nothing ||
            _vfail("Message.header union has a value but no tag")
    elseif tag == 0x01
        valp === nothing &&
            _vfail("Message.header union has a tag but no value")
        verify_Schema(bytes, valp, ctx, depth + 1)
    elseif tag == 0x02
        valp === nothing &&
            _vfail("Message.header union has a tag but no value")
        verify_DictionaryBatch(bytes, valp, ctx, depth + 1)
    elseif tag == 0x03
        valp === nothing &&
            _vfail("Message.header union has a tag but no value")
        verify_RecordBatch(bytes, valp, ctx, depth + 1)
    elseif tag == 0x04
        _vfail("Message.header union member Tensor is outside the generated schemas")
    elseif tag == 0x05
        _vfail("Message.header union member SparseTensor is outside the generated schemas")
    else
        _vfail("Message.header union has unknown tag")
    end
    _vfield(t, 3, 8)
    _vtablevector(t, 4, verify_KeyValue, ctx, depth)
    return nothing
end

function verifyroot_Message(bytes::Vector{UInt8}, ctx::VerifyContext)
    length(bytes) >= 4 || _vfail("missing root offset")
    root = Int64(_vu32(bytes, Int64(0)))
    root >= 4 || _vfail("invalid root offset")
    verify_Message(bytes, root, ctx, 0)
    return nothing
end

