# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# GENERATED by tools/fbsgen.jl from apache/arrow format/*.fbs —
# do not edit by hand; rerun the generator against the current spec.

module Flatbuf

using EnumX
using ..FlatBuffers

include("Schema.jl")
include("File.jl")
include("Message.jl")
# Hand-maintained, schema-independent verifier runtime; the generated
# walkers in Verifier.jl call into it.
include("VerifierRuntime.jl")
include("Verifier.jl")

end # module
